tinkoff-mobile-tech/AcquiringSdkAndroid

- changelog.md
- core/src/main/java/ru/tinkoff/acquiring/sdk/AcquiringSdk.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/AcquiringRequest.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/utils/CryptoUtils.kt
- gradle.properties
- readme.md
- sample/src/main/java/ru/tinkoff/acquiring/sample/SampleApplication.kt
- sample/src/main/java/ru/tinkoff/acquiring/sample/utils/SessionParams.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/TinkoffAcquiring.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/models/options/screen/BaseAcquiringOptions.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/models/options/screen/BaseCardsOptions.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/models/options/screen/PaymentOptions.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/BaseAcquiringActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/NotificationPaymentActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/SavedCardsActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/fragments/PaymentFragment.kt
Changed version to 2.4.0, recreated from [this](https://github.com/TinkoffCreditSystems/AcquiringSdkAndroid/pull/51) PR.
> 2.4.0 Sdk does not accept *password* parameter now

- changelog.md
- core/src/main/java/ru/tinkoff/acquiring/sdk/utils/CardValidator.kt
- gradle.properties
- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/MainActivity.kt
- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/PayableActivity.kt
- sample/src/main/java/ru/tinkoff/acquiring/sample/utils/PaymentNotificationManager.kt
- sample/src/main/java/ru/tinkoff/acquiring/sample/utils/SettingsSdkManager.kt
- sample/src/main/res/values-ru/strings.xml
- sample/src/main/res/values/preferences_keys.xml
- sample/src/main/res/values/strings.xml
- sample/src/main/res/xml/settings.xml
- ui/src/main/java/ru/tinkoff/acquiring/sdk/adapters/CardsViewPagerAdapter.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/models/options/FeaturesOptions.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/customview/editcard/EditCard.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/customview/editcard/validators/CardValidator.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/fragments/AttachCardFragment.kt
Added option to disable validation of card expiry date; expiry date is not validated by default
> Added option to disable validation of card expiry date

- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/SavedCardsActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/customview/BottomContainer.kt
Need handle click outside on delete dialog.
[card_remove_click_outside.webm](https://user-images.githubusercontent.com/37448471/196461628-a9a20b06-241b-4c3f-b4a4-6a3b1a78c849.webm)
> MC-6727 close custom delete dialog when user click outside

- .github/workflows/merge_request.yml
added a test run to the PR-in-version workflow
> MC-6880 add test pipeline on merge in version branch like vX.X.X

- core/src/main/java/ru/tinkoff/acquiring/sdk/AcquiringSdk.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/network/NetworkClient.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/AcquiringRequest.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/Submit3DSAuthorizationWebViewRequest.kt
- core/src/test/java/ru/tinkoff/acquiring/sdk/requests/Submit3DSAuthorizationWebViewRequestTest.kt
- core/src/test/java/ru/tinkoff/acquiring/sdk/requests/base/BaseAsdkRequestTest.kt
- gradle/versions.gradle
- sample/build.gradle
- ui/build.gradle
- ui/src/main/java/ru/tinkoff/acquiring/sdk/threeds/ThreeDsSubmitV2Delegate.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/BaseAcquiringActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/ThreeDsActivity.kt
- ui/src/test/java/BaseAsdkUiTest.kt
- ui/src/test/java/ThreeDsSubmitDelegateTest.kt
Добавил необохдимые параметры для Submit3DSAuthorizationV2 в browser-flow
> Submit3DSAuthorizationV2 в Webview

- changelog.md
- migration.md
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/customview/editcard/CardPaymentSystem.kt
+миграция к [этим](https://github.com/Tinkoff/AcquiringSdkAndroid/pull/82) изменениям
> MC-7179 fix maestro/up recognition

- changelog.md
- core/src/main/java/ru/tinkoff/acquiring/sdk/responses/AddCardResponse.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/responses/AttachCardResponse.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/threeds/ThreeDsHelper.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/AttachCardViewModel.kt
Доработки механизма 3dsv2 для привязки карт мир
> MC-7189  доработки флоу привязки 

- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/AttachCardViewModel.kt
дополнительная проверка на 2 версию 3дса
> MC-7189 3ds mir

- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/PayableActivity.kt
- sample/src/main/res/layout/activity_details.xml
- sample/src/main/res/values/styles.xml
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/YandexButtonFragment.kt
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/YandexPayError.kt
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/YandexPayResult.kt
- yandexpay/src/main/res/layout/acq_fragment_yandex_pay.xml
- yandexpay/src/main/res/layout/acq_view_yandex_pay_button.xml
- yandexpay/src/main/res/values/styles.xml
Добавил атрибуты в тему для кастомизации яндекс кнопки
> MC-7594 Настраевымые Cтили для кнопки

- core/src/main/java/ru/tinkoff/acquiring/sdk/models/paysources/YandexPay.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/AcquiringRequest.kt
- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/PayableActivity.kt
- ui/src/main/AndroidManifest.xml
- ui/src/main/java/ru/tinkoff/acquiring/sdk/TinkoffAcquiring.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/models/AsdkState.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/PaymentProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/PaymentType.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/YandexPaymentActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/fragments/YandexPaymentStubFragment.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/utils/Money.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/PaymentViewModel.kt
- ui/src/main/res/layout/acq_fragment_yandex_stub.xml
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/TinkoffAcquiringYandexExt.kt
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/YandexButtonFragment.kt
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/YandexPayError.kt
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/models/YandexPayData.kt
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/models/YandexPayDataMapper.kt
- yandexpay/src/test/java/ru/tinkoff/acquiring/yandexpay/MoneyUtilsTest.kt
инициализация платежной сессии после успешного получения  яндекс токена
> Mc 7363 init request

- sample/build.gradle
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/dialog/OpenBankProgressDialogFragment.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/dialog/PaymentFailureDialogFragment.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/dialog/PaymentFailureInsufficientFundsDialogFragment.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/dialog/PaymentSuccessDialogFragment.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/customview/LoaderButton.kt
- ui/src/main/res/color/acq_secondary_button_text_selector.xml
- ui/src/main/res/drawable/acq_bottom_sheet_bg.xml
- ui/src/main/res/drawable/acq_button_flat_bg.xml
- ui/src/main/res/drawable/acq_button_secondary_bg.xml
- ui/src/main/res/drawable/acq_ic_check_circle_positive.xml
- ui/src/main/res/drawable/acq_ic_cross_circle.xml
- ui/src/main/res/layout/acq_fragment_open_bank_progress.xml
- ui/src/main/res/layout/acq_fragment_payment_failure.xml
- ui/src/main/res/layout/acq_fragment_payment_failure_insufficient_funds.xml
- ui/src/main/res/layout/acq_fragment_payment_success.xml
- ui/src/main/res/values/attrs.xml
- ui/src/main/res/values/colors.xml
- ui/src/main/res/values/styles.xml
> MC-7550 bottom sheet dialogs

- core/src/main/java/ru/tinkoff/acquiring/sdk/network/NetworkClient.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/AcquiringRequest.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/FinishAuthorizeRequest.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/responses/FinishAuthorizeResponse.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/PaymentProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/threeds/ThreeDsHelper.kt
прохождение 3ds версии 2.0 при оплате с помощью яндекс токена.
> Mc 7366 3ds passing yandex

- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/dialog/DialogActivityExt.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/dialog/PaymentLCEDialogFragment.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/dialog/PaymentProgressDialogFragment.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/dialog/PaymentSuccessDialogFragment.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/YandexPaymentActivity.kt
- ui/src/main/res/anim/acq_slide_down.xml
- ui/src/main/res/anim/acq_slide_up.xml
- ui/src/main/res/layout/acq_fragment_payment_failure.xml
- ui/src/main/res/layout/acq_fragment_payment_lce.xml
- ui/src/main/res/layout/acq_fragment_payment_progress.xml
- ui/src/main/res/layout/acq_fragment_payment_success.xml
- ui/src/main/res/values/styles.xml
прохождение яндекс платежа в No3ds, шторки для показf статусов.
> MC-7364 payment complete

- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/AcquiringRequest.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/FinishAuthorizeRequest.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/GetTerminalPayMethodsRequest.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/PaymentState.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/YandexPaymentProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/threeds/ThreeDsHelper.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/YandexPaymentActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/ViewModelProviderFactory.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/YandexPaymentViewModel.kt
- yandexpay/src/test/java/ru/tinkoff/acquiring/yandexpay/GetTerminalPayMethodsTest.kt
изменения, для облегчения тестирования
> MC-7666 - изменения, для облегчения тестирования

- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/PayableActivity.kt
- sample/src/main/res/values-ru/strings.xml
- sample/src/main/res/values/strings.xml
- sample/src/main/res/xml/settings.xml
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/TinkoffAcquiringYandexExt.kt
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/YandexButtonFragment.kt
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/YandexPayResult.kt
добавления тоглла яндекс в семпл + добавление возможности указания payment options в яндекс фрагменте в рантайме
> MC-7763 добавления тоглла яндекс в семпл

- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/PayableActivity.kt
- ui/src/main/res/values-ru/strings.xml
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/TinkoffAcquiringYandexExt.kt
> MC-7843 мелкие правки перед релизом

- ui/src/main/java/ru/tinkoff/acquiring/sdk/TinkoffAcquiring.kt
Добавил очищения скоупа для асинхронных вызовов TinkoffAcq
> Mc 7844 scopes refactoring

- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/PayableActivity.kt
> MC-7850 правки семпла при закрытии яндекса

- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/YandexPaymentProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/ViewModelProviderFactory.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/YandexPaymentViewModel.kt
- ui/src/test/java/yandex/YandexPaymentProcessEnv.kt
- yandexpay/src/main/java/ru/tinkoff/acquiring/yandexpay/TinkoffAcquiringYandexExt.kt
yandex pay combi-init  + расширенный ЖЦ для yandexPaymentProcess
> MC-7884 - yandex pay combi-init 

- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/BaseAcquiringActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/YandexPaymentActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/ViewModelProviderFactory.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/YandexPaymentViewModel.kt
нахождение vm в старой фабрике вело к крашу, тк процесс иницилизируется лениво
> MC-7884 - новая vmFactory для яндекс пей

- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/RemoveCardRequest.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/presentation/CardsListViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/ui/CardsListActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/ui/CardsListState.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/common/carddatainput/CardDataInputFragment.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/utils/AcqSnackBarHelper.kt
- ui/src/main/res/layout/acq_activity_card_list.xml
- ui/src/main/res/values-ru/strings.xml
- ui/src/main/res/values/strings.xml
> Mc 8148 bugs flow

- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/RemoveCardRequest.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/presentation/CardsListViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/ui/CardsListActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/ui/CardsListState.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/common/carddatainput/CardDataInputFragment.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/common/carddatainput/CardNumberFormatter.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/utils/AcqSnackBarHelper.kt
- ui/src/main/res/layout/acq_activity_card_list.xml
- ui/src/main/res/values-ru/strings.xml
- ui/src/main/res/values/strings.xml
- ui/src/test/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/CardsDeleteViewModelTest.kt
> MC-8148 флоу управления картами 2.0

- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/RemoveCardRequest.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/common/carddatainput/CardDataInputFragment.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/payment/ui/PaymentByCardActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/smartfield/BaubleClearOrScanButton.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/utils/FragmentExt.kt
- ui/src/main/res/drawable/acq_ic_card_frame.xml
возможность сканированния карты на новой форме
> MC-8137 card scanner

- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/DetailsActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/YandexPaymentActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/YandexPaymentViewModel.kt
> MC-7884 crash yandex pay fix

- gradle.properties
- ui/src/main/java/ru/tinkoff/acquiring/sdk/TinkoffAcquiring.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/PaymentByCardProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/adapters/CardsListAdapter.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/presentation/CardsListViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/ui/CardsListActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/ui/CardsListState.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/common/carddatainput/CvcComponent.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/dialog/PaymentStatusFormExt.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/MainPaymentFormStub.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/payment/ui/ChosenCardComponent.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/payment/ui/PaymentByCardActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/payment/ui/PaymentByCardViewModel.kt
фиксы флоу оплаты перевыбранной карты
> MC - 8241  фиксы флоу оплаты перевыбранной карты

- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/common/savedcard/SavedCardsRepository.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/MainPaymentFormFactory.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/MainPaymentFormUi.kt
- ui/src/main/res/drawable/acq_button_spb_bg.xml
- ui/src/main/res/layout/acq_maiform_primary_button.xml
- ui/src/main/res/values-night/colors.xml
- ui/src/main/res/values/colors.xml
- ui/src/test/java/common/EnvExt.kt
- ui/src/test/java/main/MainPaymentFormFactoryEnv.kt
- ui/src/test/java/main/MainPaymentFormFactoryTest.kt
- ui/src/test/java/sbp/SbpTestEnvironment.kt
Алгоритм выбора основной кнопки
> MC-8234 - алгоритм отображения основной кнопки

- core/src/main/java/ru/tinkoff/acquiring/sdk/responses/GetTerminalPayMethodsResponse.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/MainPaymentFormStub.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/MainPaymentFormFactory.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/MainPaymentFormUi.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/MainPaymentFormViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/MainPaymentFromUtils.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/primary/PrimaryButtonConfigurator.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/secondary/SecondButtonConfigurator.kt
- ui/src/test/java/main/MainPaymentFormFactoryEnv.kt
- ui/src/test/java/main/MainPaymentFormFactoryTest.kt
- ui/src/test/java/main/MainPaymentFormSecondBlockTest.kt
Алгоритм определние блока дополнительных спобов оплаты + рефакторинг, тесты
> MC-8285 -  Алгоритм определние блока дополнительных спобов оплаты

- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/PayableActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/PaymentByCardProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/adapters/CardsListAdapter.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/common/cardpay/CardPayComponent.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/common/result/AcqPaymentResult.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/MainPaymentFormActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/navigation/MainFormContract.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/navigation/MainFormNavController.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/vm/MainFormInputCardViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/vm/MainPaymentFormFactory.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/vm/MainPaymentFormViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/payment/ui/PaymentByCard.kt
- ui/src/main/res/layout/acq_main_from_activity.xml
MC-8228  новая навигация на платежной форме
> MC-8228 - navigation

- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/cards/list/ui/CardsListActivity.kt
- ui/src/main/res/layout/acq_card_list_content.xml
new card icon for add card or other card pay
> Mc 8296 new icon card

- core/src/main/java/ru/tinkoff/acquiring/sdk/exceptions/AcquiringSdkException.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/exceptions/AcquiringSdkTimeoutException.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/models/enums/ResponseStatus.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/network/NetworkClient.kt
- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/CartActivity.kt
- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/DetailsActivity.kt
- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/PayableActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/SbpPaymentProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/base/AcqPaymentState.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/pooling/GetStatusMethod.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/pooling/GetStatusPooling.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/AttachCardActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/utils/CoroutineManager.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/utils/FlowExt.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/PaymentViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/ThreeDsViewModel.kt
- ui/src/test/java/ru/tinkoff/acquiring/sdk/payment/pooling/GetStatusPolingTest.kt
- ui/src/test/java/ru/tinkoff/acquiring/sdk/payment/pooling/GetStatusPoolingTest.kt
- ui/src/test/java/sbp/SbpTestEnvironment.kt
Рефакторинг алгоритма опроса Состояния платежа
> Eacqapw 4082 get state 3.0.0

- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/PayableActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/models/ViewState.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/BaseAcquiringActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/PaymentActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/SavedCardsActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/ThreeDsActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/ui/activities/TransparentActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/utils/IntentExt.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/BaseAcquiringViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/PaymentViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/ThreeDsViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/viewmodel/YandexPaymentViewModel.kt
Добавление возможности получения payment id из контракта ошибки.
> EACQAPW-4370 - add payment id in error contract 

- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/DetailsActivity.kt
- sample/src/main/java/ru/tinkoff/acquiring/sample/ui/PayableActivity.kt
новый способ работать с результатом активности
> EACQAPW-4401_api_result_usage 

- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/PaymentByCardProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/RecurrentPaymentProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/methods/ChargeMethods.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/methods/Check3DsVersionMethods.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/methods/FinishAuthorizeMethods.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/methods/InitMethods.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/process/MainFormPaymentProcessMapper.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/vm/MainPaymentFormViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/payment/ui/PaymentByCardViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/utils/CoroutineManager.kt
- ui/src/test/java/common/AcquiringResponseStub.kt
- ui/src/test/java/ru/tinkoff/acquiring/sdk/payment/RecurrentPaymentProcessTest.kt
обработка рекуррентного платежа, новый флоу…, процесс, тесты, бизнес логика
> MC-8039-reccurent_process domain

- ui/src/main/java/ru/tinkoff/acquiring/sdk/models/options/screen/PaymentOptions.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/models/options/screen/analytics/MainFormAnalytics.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/PaymentProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/navigation/MainFormNavController.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/MainPaymentForm.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/analytics/MainFormAnalyticsDelegate.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/vm/MainFormInputCardViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/vm/MainPaymentFormFactory.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/vm/MainPaymentFormViewModel.kt
- ui/src/test/java/main/MainFormAnalyticsTest.kt
- ui/src/test/java/main/MainPaymentFormViewModelEnv.kt
добавить поля в init для аналитики работы главной платежной формы
> MC-8275 - добавить поля в init для аналитики.

- gradle.properties
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/MainPaymentFormActivity.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/navigation/MainFormNavController.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/mainform/presentation/vm/MainPaymentFormViewModel.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/redesign/recurrent/presentation/RecurrentPaymentViewModel.kt
- ui/src/main/res/layout/acq_payment_status_form.xml
фикс багов с рекурентом и шторкой , а так же навигация на оплату по карте
> EACQAPW-4610 - bugs fixes

- core/src/main/java/ru/tinkoff/acquiring/sdk/AcquiringSdk.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/network/AcquiringApi.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/requests/MirPayLinkRequest.kt
- core/src/main/java/ru/tinkoff/acquiring/sdk/responses/MirPayResponse.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/MirPayProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/TpayProcess.kt
- ui/src/main/java/ru/tinkoff/acquiring/sdk/payment/methods/MirPayMethods.kt
Реализован domain слой процесса оплаты через MirPay под дип-линку
> MC-8925: Реализован процесс оплаты через MirPay
